import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";
import Sidebar from "../components/Sidebar";
import BootstrapClient from "@/components/BootstrapClient";


export const metadata: Metadata = {
  title: "Banco - Gestión de Productos Financieros",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <BootstrapClient />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
